"""The CurseForge fingerprint and the file digests.

Verifying this matters more than it looks. A wrong fingerprint does not raise, does not warn,
and does not look wrong in a report — it simply never matches, so every CurseForge mod is
reported as "unresolved" and the admin concludes the feature does not work. And it cannot be
checked end to end in this repository, because the fingerprint endpoint needs an API key.

So it is checked against something built from a different source instead:
``tools/murmur2_cf.js`` is a JavaScript transcription of the C# client published in
CurseForge's own ecosystem. Two independent ports agreeing on random input is the strongest
available evidence short of a live call, and the vectors below are pinned from it so the
suite still has coverage when node is not installed.
"""

import hashlib
import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

from mod_update_checker.fingerprint import (
    CF_IGNORED_BYTES,
    CF_SEED,
    curseforge_fingerprint,
    digests_of_file,
    strip_cf_whitespace,
)

REPO = Path(__file__).resolve().parent.parent
JS_IMPLEMENTATION = REPO / "tools" / "murmur2_cf.js"

#: ``(byte values, fingerprint)``, generated by ``tools/murmur2_cf.js``.
JS_VECTORS = [
    ([], 0),
    ([0, 1, 2, 3], 3050564819),
    ([1, 2, 3], 2032630479),
    ([97, 98, 99], 1621425345),
    # Bytes 32/9/10/13 are all stripped, so this is the empty input.
    ([32, 9, 10, 13], 0),
    ([0, 1, 2, 3, 4], 813985283),
    ([255, 255, 255], 1028598673),
    ([26, 3, 32, 45, 32, 102, 97, 98, 114, 105, 99], 2168554823),
]


def test_seed_and_ignored_bytes_are_what_curseforge_documents():
    """The two constants that make this *CurseForge's* MurmurHash2 rather than plain
    MurmurHash2: seed 1, and four whitespace bytes dropped before hashing."""
    assert CF_SEED == 1
    assert CF_IGNORED_BYTES == frozenset((0x09, 0x0A, 0x0D, 0x20))


@pytest.mark.parametrize("data,expected", JS_VECTORS)
def test_matches_pinned_vectors(data, expected):
    assert curseforge_fingerprint(bytes(data)) == expected


def test_empty_input_is_zero():
    assert curseforge_fingerprint(b"") == 0
    assert curseforge_fingerprint(b" \t\r\n \t") == 0


def test_whitespace_bytes_do_not_affect_the_result():
    """The whole point of the normalisation step."""
    plain = b"the quick brown fox"
    assert curseforge_fingerprint(plain) == curseforge_fingerprint(
        b"the \t quick \r\n brown \t fox"
    )


def test_other_bytes_are_not_stripped():
    """Only those four bytes. A stray 0x0B (vertical tab) is data, not whitespace."""
    assert curseforge_fingerprint(b"a\x0bb") != curseforge_fingerprint(b"ab")


def test_strip_cf_whitespace_returns_input_untouched_when_clean():
    """The fast path has to be an identity, not just an equality, so no copy is made."""
    payload = b"nowhitespaceatall"
    assert b" " not in payload and b"\t" not in payload
    assert strip_cf_whitespace(payload) is payload


def test_result_is_an_unsigned_32_bit_integer():
    for payload in (b"a", b"x" * 1000, bytes(range(256)), b"\xff" * 64):
        value = curseforge_fingerprint(payload)
        assert 0 <= value <= 0xFFFFFFFF


def test_is_deterministic_and_order_sensitive():
    assert curseforge_fingerprint(b"abcdef") == curseforge_fingerprint(b"abcdef")
    assert curseforge_fingerprint(b"abcdef") != curseforge_fingerprint(b"fedcba")


@pytest.mark.parametrize("length", list(range(0, 24)))
def test_every_tail_length_is_handled(length):
    """MurmurHash2 folds the remaining 1..3 bytes in a fall-through switch; a port that
    drops one of those cases only breaks for some input lengths."""
    payload = bytes((index * 37 + 11) % 256 for index in range(length))
    if all(byte in CF_IGNORED_BYTES for byte in payload):
        pytest.skip("payload normalises away to nothing")
    assert curseforge_fingerprint(payload) != 0


def _node() -> str:
    """Path to a node binary, or ``""`` when there is none.

    ``shutil.which`` is the whole mechanism; ``MUC_NODE`` is an escape hatch for a machine
    that keeps node somewhere off ``PATH``. Nothing environment-specific is hardcoded — the
    cross-language check is a nice-to-have, and a path baked into this repository would be
    useless on every machine except the one it was written on.
    """
    override = os.environ.get("MUC_NODE", "").strip()
    if override and Path(override).is_file():
        return override
    return shutil.which("node") or ""


NODE = _node()

node_required = pytest.mark.skipif(
    not NODE or not JS_IMPLEMENTATION.is_file(),
    reason="node is not available, so the cross-language check cannot run",
)


@node_required
def test_matches_independent_javascript_implementation():
    """Cross-language check on pseudo-random input, across every tail length.

    The Python function has no ``seed`` parameter — CurseForge's seed is a constant — so the
    comparison is always made at seed 1. That the JavaScript side actually *uses* its seed
    is asserted separately below, otherwise this check could pass while both sides quietly
    ignored it.
    """
    import random

    generator = random.Random(20261007)
    lengths = list(range(0, 20)) + [31, 32, 33, 64, 100, 255, 256, 257, 1000]
    inputs = [
        bytes(generator.randrange(256) for _ in range(length)) for length in lengths
    ]

    for payload_bytes in inputs:
        completed = subprocess.run(
            [NODE, str(JS_IMPLEMENTATION)],
            input=json.dumps({"data": list(payload_bytes), "seed": 1}),
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert completed.returncode == 0, completed.stderr
        assert int(completed.stdout.strip()) == curseforge_fingerprint(payload_bytes), (
            "python and javascript disagree on {}".format(list(payload_bytes))
        )


@node_required
def test_javascript_implementation_honours_its_seed():
    """Guards the guard: a cross-check against an implementation that ignored the seed would
    not be checking the seed-dependent part of the algorithm at all."""
    payload = [1, 2, 3]

    def run(seed: int) -> str:
        completed = subprocess.run(
            [NODE, str(JS_IMPLEMENTATION)],
            input=json.dumps({"data": payload, "seed": seed}),
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert completed.returncode == 0, completed.stderr
        return completed.stdout.strip()

    assert run(1) != run(0)


@node_required
def test_javascript_implementation_strips_whitespace_too():
    """Guards the guard: if the JS port did not normalise, the cross-check above would be
    comparing two implementations of the wrong algorithm."""
    completed = subprocess.run(
        [NODE, str(JS_IMPLEMENTATION)],
        input=json.dumps({"data": [32, 9, 10, 13]}),
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert completed.stdout.strip() == "0"


# --------------------------------------------------------------------------------------
# digests_of_file
# --------------------------------------------------------------------------------------


def test_digests_of_file_matches_independent_computation(tmp_path):
    payload = b"PK\x03\x04" + bytes(range(256)) * 7 + b"\n \t\r\n"
    path = tmp_path / "blob.bin"
    path.write_bytes(payload)

    with open(path, "rb") as handle:
        sha1, sha512, fingerprint, size = digests_of_file(handle)

    assert sha1 == hashlib.sha1(payload).hexdigest()
    assert sha512 == hashlib.sha512(payload).hexdigest()
    assert fingerprint == curseforge_fingerprint(payload)
    assert size == len(payload)


def test_digests_of_file_streams_consistently(tmp_path, monkeypatch):
    """The single-pass reader must give the same answer as hashing the whole buffer, even
    when the read size does not divide the file length."""
    payload = bytes((index * 13 + 7) % 256 for index in range(5000))
    path = tmp_path / "blob.bin"
    path.write_bytes(payload)

    import mod_update_checker.fingerprint as module

    monkeypatch.setattr(module, "_READ_CHUNK", 7)
    with open(path, "rb") as handle:
        sha1, sha512, fingerprint, size = module.digests_of_file(handle)

    assert sha1 == hashlib.sha1(payload).hexdigest()
    assert sha512 == hashlib.sha512(payload).hexdigest()
    assert fingerprint == curseforge_fingerprint(payload)
    assert size == len(payload)


def test_digests_of_empty_file(tmp_path):
    path = tmp_path / "empty.bin"
    path.write_bytes(b"")
    with open(path, "rb") as handle:
        sha1, sha512, fingerprint, size = digests_of_file(handle)
    assert sha1 == hashlib.sha1(b"").hexdigest()
    assert fingerprint == 0
    assert size == 0
